### ISSUE TITLE
sporadic add owner migration failure

### ISSUE THREAD

**Issue by Damrod** [42AGV/ft_transcendence#457] opened 2023-01-25 15:00 UTC
If you flush your docker volumes (as I continuously do), and run make, it will sporadically fail (once every 10 times, maybe) like this:

```
make migrate
make[1]: Entering directory '/home/alvaro/ft_transcendence'
docker-compose exec transcendence-app npm run knex:migrate:dev -w transcendence-app

> transcendence-app@0.0.1 knex:migrate:dev
> knex migrate:latest

Requiring external module ts-node/register
Using environment: development
migration file "20221206105801_add_web_owner_user.ts" failed
migration failed with error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/b5bb33219cfd3f4ff858ba6724478e83'
ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/b5bb33219cfd3f4ff858ba6724478e83'
Error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/b5bb33219cfd3f4ff858ba6724478e83'
npm ERR! Lifecycle script `knex:migrate:dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: transcendence-app@0.0.1 
npm ERR!   at location: /service/transcendence-app 
make[1]: *** [Makefile:92: migrate] Error 1
make[1]: Leaving directory '/home/alvaro/ft_transcendence'
make: *** [Makefile:10: all] Error 2

```
This is not often an issue, but may critically be an issue when we have corrections, since we have to have migrations, or a way around them, there as well. We should fix it.

**Comment by Damrod** [comment] 2023-01-25 22:13
I've ran make on a clean slate 6 times and it has failed twice. So my estimation was wron, this is more serious than expected. Last time, with these changes:
```
Index: transcendence-app/migrations/20221206105801_add_web_owner_user.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/transcendence-app/migrations/20221206105801_add_web_owner_user.ts b/transcendence-app/migrations/20221206105801_add_web_owner_user.ts
--- a/transcendence-app/migrations/20221206105801_add_web_owner_user.ts	(revision 67ca65d1362e47c3e74641dbe3a9a775f17ab38f)
+++ b/transcendence-app/migrations/20221206105801_add_web_owner_user.ts	(date 1674683544794)
@@ -18,15 +18,56 @@
 };
 
 export async function up(knex: Knex): Promise<void> {
-  const adminAvatar = await createRandomAvatar();
-  const adminWithPassword = await createAdminWithPassword(adminAvatar.id);
-  // Inserts admin entry
-  await knex('localfile').insert(adminAvatar);
-  const [admin, _] = await knex('users')
-    .insert(adminWithPassword)
-    .returning('*');
-  await knex('usertorole').insert({ id: admin.id, role: 'owner' });
-  await knex('usertorole').insert({ id: admin.id, role: 'moderator' });
+  try {
+    const adminAvatar = await createRandomAvatar();
+    try {
+      const adminWithPassword = await createAdminWithPassword(adminAvatar.id);
+      // Inserts admin entry
+      try {
+        await knex('localfile').insert(adminAvatar);
+        try {
+          const [admin, _] = await knex('users')
+            .insert(adminWithPassword)
+            .returning('*');
+          try {
+            await knex('usertorole').insert({ id: admin.id, role: 'owner' });
+            try {
+              await knex('usertorole').insert({
+                id: admin.id,
+                role: 'moderator',
+              });
+            } catch (e) {
+              console.log(
+                "failed at await knex('usertorole').insert({ id: admin.id, role: 'moderator' });\n",
+              );
+              throw e;
+            }
+          } catch (e) {
+            console.log(
+              "failed at await knex('usertorole').insert({ id: admin.id, role: 'owner' });",
+            );
+            throw e;
+          }
+        } catch (e) {
+          console.log(
+            "failed at await knex('users')\n" +
+              '    .insert(adminWithPassword)\n' +
+              "    .returning('*');",
+          );
+          throw e;
+        }
+      } catch (e) {
+        console.log("failed at knex('localfile').insert(adminAvatar)");
+        throw e;
+      }
+    } catch (e) {
+      console.log('failed at createAdminWithPassword');
+      throw e;
+    }
+  } catch (e) {
+    console.log('failed at create random avatar');
+    throw e;
+  }
 }
 
 export async function down(knex: Knex): Promise<void> {
```
I get these debugging lines:
```
make migrate
make[1]: Entering directory '/home/alvaro/ft_transcendence'
docker-compose exec transcendence-app npm run knex:migrate:dev -w transcendence-app

> transcendence-app@0.0.1 knex:migrate:dev
> knex migrate:latest

Requiring external module ts-node/register
Using environment: development
failed at create random avatar
migration file "20221206105801_add_web_owner_user.ts" failed
migration failed with error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/a69ba753dd6bd00ac7d983980be3b19f'
ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/a69ba753dd6bd00ac7d983980be3b19f'
Error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/a69ba753dd6bd00ac7d983980be3b19f'
npm ERR! Lifecycle script `knex:migrate:dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: transcendence-app@0.0.1 
npm ERR!   at location: /service/transcendence-app 
make[1]: *** [Makefile:92: migrate] Error 1
make[1]: Leaving directory '/home/alvaro/ft_transcendence'
make: *** [Makefile:10: all] Error 2
```
So the broken path is in the add avatar, and possibly localFileService. Which is confusing, because we're calling this method thousands of times in the seeding, and it was never complaining. Why should it break so frequently when adding a single user.

**Comment by gbudau** [comment] 2023-01-26 19:51
Does this error happen when deleting the volumes while the app is running?

Could you provide the commands to reproduce the error?

**Comment by Damrod** [comment] 2023-01-26 22:41
Running app, then:
`make clean`
after it finishes:
`docker volume prune` ... ->y
after it finishes
`make`.

It happens rarely. Maybe it's a problem with my workstation. I don't know.

**Comment by Damrod** [comment] 2023-02-07 22:18
I haven't seen again. But then again, I'm rarely pruning my volumes lately.

**Comment by gbudau** [comment] 2023-02-08 19:00
For what is worth, I've run this command, and there was no error:

```sh
for _ in {1..50}; do make clean && docker volume prune -f && make; done
```

I know the sample size is small :sweat_smile:. If you agree, we could close this issue and reopen it if this error appears again.

**Comment by Damrod** [comment] 2023-02-08 20:20
Let's close it. Probably it was my docker with its 38 GB of garbage.

**Comment by Damrod** [comment] 2023-02-10 23:19
```
Requiring external module ts-node/register
Using environment: development
migration file "20221206105801_add_web_owner_user.ts" failed
migration failed with error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/fdc6dcd399aa41789186533f0be9a3c5'
ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/fdc6dcd399aa41789186533f0be9a3c5'
Error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/fdc6dcd399aa41789186533f0be9a3c5'
npm ERR! Lifecycle script `knex:migrate:dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: transcendence-app@0.0.1 
npm ERR!   at location: /service/transcendence-app 
make[1]: *** [Makefile:93: migrate] Error 1
make[1]: Leaving directory '/home/alvaro/ft_transcendence'
make: *** [Makefile:10: all] Error 2
```

Oh look, I've seen it again

**Comment by Damrod** [comment] 2023-03-18 16:44
I ran it ten times locally, in its current, latest form, and I saw this the third iteration:
```
 ⠿ Container ft_transcendence-db-1                       Healthy                                                                                              7.5s
 ⠿ Container ft_transcendence-memcached-1                Started                                                                                              2.0s
 ⠿ Container ft_transcendence-migrations-1               Exited                                                                                              20.7s
 ⠿ Container ft_transcendence-transcendence-app-1        Created                                                                                              0.1s
 ⠿ Container ft_transcendence-webapp-1                   Created                                                                                              0.1s
 ⠿ Container ft_transcendence-nginx-1                    Created                                                                                              0.1s
service "migrations" didn't completed successfully: exit 1
```

I'm running it 300 for production and 300 times for dev remotely, in a runner here in github, to see if I can only see this locally. If I cannot see it remotely, I think I'll close the issue.

**Comment by Damrod** [comment] 2023-03-18 16:45
Maybe we could have some kind of rerun of the service in case it doesn't complete succesfully? This should solve all problems in any case, I think.

**Comment by gbudau** [comment] 2023-03-18 17:55
> Maybe we could have some kind of rerun of the service in case it doesn't complete succesfully? This should solve all problems in any case, I think.

Good idea. We could add a [restart policy](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy) to the migrations service.

**Comment by Damrod** [comment] 2023-03-19 07:20
Seen this
```
2023-03-18T16:27:00.2452670Z ERROR: for transcendence-app  Container "555cbda4c620" exited with code 1.
```
in line 7867,
then 
```
2023-03-18T17:08:39.3342071Z ERROR: for transcendence-app  Container "e0871c89b791" exited with code 1.
```
in line 28721 and
```
2023-03-18T18:03:56.9693688Z ERROR: for transcendence-app  Container "7b425553a2b9" exited with code 1.
```
in line 56395 of the [dev test](https://github.com/42AGV/ft_transcendence/suites/11651981214/logs?attempt=1). Sadly I don't have more verbose logs than that. I will be working on them today.

**Comment by Damrod** [comment] 2023-03-19 08:23
Sadly, it reproduces remotely as well, [here](https://github.com/42AGV/ft_transcendence/actions/runs/4459619470/jobs/7832214491#step:4:3423) 
```
migrations_1  | Error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/7e6a795e6096d0b29888f4f61a3fcd71'
migrations_1  | migration file "20221206105801_add_web_owner_user.ts" failed
migrations_1  | migration failed with error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/7e6a795e6096d0b29888f4f61a3fcd71'
migrations_1  | ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/7e6a795e6096d0b29888f4f61a3fcd71'
migrations_1  | Error: ENOENT: no such file or directory, open '/var/lib/transcendence-app/avatars/7e6a795e6096d0b29888f4f61a3fcd71'
e7a33230adc2   ft_transcendence/transcendence-app-dev   "/usr/bin/dumb-init …"   11 seconds ago   Up 10 seconds                        ft_transcendence_migrations_1
migrations_1  | npm ERR! Lifecycle script `knex:migrate:dev` failed with error: 
migrations_1  | npm ERR! Error: command failed 
migrations_1  | npm ERR!   in workspace: transcendence-app@0.0.1 
migrations_1  | npm ERR!   at location: /service/transcendence-app 
ft_transcendence_migrations_1 exited with code 1
```

**Comment by gbudau** [comment] 2023-03-19 10:45
Could you please check #600, I think this might happen because we use `fs.mkdir`, which is `async`, without passing a callback. So if the directory gets created after the `createWriteStream` starts writing to the file, it throws an error.
I changed it to use the `fsPromises.mkdir` and added `await`.

**Comment by Damrod** [comment] 2023-03-19 11:27
> createWriteStream

Yes, I think so. I made [these](https://github.com/42AGV/ft_transcendence/pull/597/files) changes to prove it. Locally I'm doing the mkdir inside a settimeout, and I see the same symptoms over and over. Now, if the error comes from there, we'll see the stack trace whenever it fails (at any point in the 300s times it will try).

**Comment by gbudau** [comment] 2023-03-19 11:31
Thank you for your persistence and effort in investigating and reproducing this issue.

**Closed** 2023-03-19 14:19 UTC
Labels: 🐞 bug
